project:
  type: website

website:
  title: "Ruimtelijke Data voor de leefomgeving"
  navbar:
    left:
      - href: index.qmd
        text: Nederlandse gegevens
      - href: europa.qmd
        text: Europese gegevens
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

