project:
  type: website

website:
  title: "Ruimtelijke Data voor de leefomgeving"
  site-url: "https://ruimtelijkedata.netlify.app"
  repo-url: https://github.com/RonaldVisser/RuimtelijkeData
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Nederlandse gegevens
      - href: europa.qmd
        text: Europese gegevens
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

