---
title: "Ruimtelijke data voor de leefomgeving"
author:
  - name: Ronald Visser
    orcid: 0000-0001-6966-1729
    email: r.m.visser@saxion.nl
    affiliation: 
      - name: Saxion University of Applied Sciences
        city: Deventer
        country: Netherlands
---

De lijst bronnen hieronder is een overzicht van relevante websites voor het vinden van data over de Nederlandse ruimtelijke omgeving, zowel onder als boven de grond. De lijst is niet compleet, maar helpt je wel op weg in het data-landschap. Let op! Er zit geen ordening in de lijst.

+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Leverancier (omschrijving)                                                  | Link                                                                                                               |
+=============================================================================+====================================================================================================================+
| PDOK (luchtfoto's, topografische kaarten, kadaster, etc):                   | <https://www.pdok.nl/>                                                                                             |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| CBS (statistische data over Nederland)                                      | <https://www.cbs.nl/>                                                                                              |
|                                                                             |                                                                                                                    |
|                                                                             | <https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/geografische-data>                                           |
|                                                                             |                                                                                                                    |
|                                                                             | <https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/wijk-en-buurtstatistieken>                                   |
|                                                                             |                                                                                                                    |
|                                                                             | <https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/informatie-voor-gemeenten/ruimtelijke-statistieken>          |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Atlas van de Leefomgeving                                                   | <https://www.atlasleefomgeving.nl/>                                                                                |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Actueel Hoogtebestand Nederland (AHN)                                       | <https://www.ahn.nl/>                                                                                              |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Topotijdreis (200 jaar topografische kaarten)                               | <https://www.topotijdreis.nl/>                                                                                     |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Erfgoed en landschap (RCE)                                                  | <https://www.cultureelerfgoed.nl/onderwerpen/bronnen-en-kaarten/overzicht>                                         |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Luchtfoto's RAF (WO2)                                                       | <https://www.wur.nl/en/library/special-collections/aerial-photographs.htm>                                         |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Diverse oude kaarten                                                        | <https://www.wur.nl/en/library/special-collections/maps-atlases.htm>                                               |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Ruimtelijke plannen                                                         | <https://www.ruimtelijkeplannen.nl/home>                                                                           |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Basis Registratie Ondergrond (BRO)                                          | <https://basisregistratieondergrond.nl/>                                                                           |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| DINOloket (ondergrond van TNO)                                              | <https://www.dinoloket.nl/>                                                                                        |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Overheid: gemeente/provincie/waterschappen/rijk                             | <https://data.overheid.nl/datasets> (diverse datasets)                                                             |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Steden, sommige steden bieden ook data aan, zoals bijvoorbeeld:             | <https://maps.amsterdam.nl/open_geodata/>                                                                          |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Beleid ruimtelijke ordening                                                 | <https://www.rijksoverheid.nl/onderwerpen/ruimtelijke-ordening-en-gebiedsontwikkeling/beleid-ruimtelijke-ordening> |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Geodata / NOVEX (omgevingsvisie)                                            | <https://www.denationaleomgevingsvisie.nl/novex/ruimtelijke+data/default.aspx>                                     |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 3DBAG                                                                       | <https://www.3dbag.nl/en/viewer>                                                                                   |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Erfgoed uit de Tweede Wereldoorlog in Drenthe (GIS)                         | <https://www.provincie.drenthe.nl/onderwerpen/cultuur-sport-vrije/cultuur/erfgoed/archeologie/erfgoed-tweede/>     |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| WKO-bodemenergietool. Ruimtelijke tool voor mogelijkheden van bodemenergie. | <https://wkotool.nl/>                                                                                              |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Grondwaterdata                                                              | <https://opendata.munisense.net/>                                                                                  |
+-----------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+

```         
Deze website is voor het laatst bijgewerkt op `r format(Sys.time(), '%d %B %Y')`.
```
